# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93f42f27edb02c1b93cf33b1c4cfa8c8dce235266a8b14337cff5e6d4796e48f87e5665bd4bad966bd4091819654dcb4f9e63d23a29e869d33073bf559c406e8

test:
  secret_key_base: 8740b1620573eba5ab9215b070c29f5b4acf84c38c15bd2fc72b063ee7fb345e45fb3a7cc6f9730739b4ac6ba3dae13f9a94b071841a186028addaa669d04c03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
